CREATE DATABASE Empresa;

USE Empresa;

CREATE TABLE Proveedores(
NIF INT UNSIGNED PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Direccion VARCHAR(80) NOT NULL
);


CREATE TABLE Productos(
ID INT UNSIGNED PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Precio FLOAT UNSIGNED NOT NULL, 
Proveedor INT UNSIGNED,
FOREIGN KEY(Proveedor)
REFERENCES Proveedores(NIF)
);

CREATE TABLE Clientes(
DNI INT UNSIGNED PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(60) NOT NULL,
Direccion VARCHAR(80) NOT NULL,
Nacimiento DATE NOT NULL,
);

CREATE TABLE Productos_Comprados(
ID_Comprado INT UNSIGNED PRIMARY KEY,
ID_Producto INT UNSIGNED,
ID_Cliente INT UNSIGNED,
FOREIGN KEY (ID_Producto)
REFERENCES Productos (ID),
FOREIGN KEY (ID_Cliente)
REFERENCES Clientes (DNI)
);
