CREATE DATABASE Aseguradora;

USE Aseguradora;

CREATE TABLE Clientes(
DNI INT UNSIGNED PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(60) NOT NULL,
Telefono VARCHAR(10) NOT NULL,
Direccion VARCHAR(80) NOT NULL,
Sexo VARCHAR(15) NOT NULL,
ANo_Carnet YEAR NOT NULL,
Cuenta_Bancaria VARCHAR(70),
Fecha DATE NOT NULL
);

CREATE TABLE Vehiculos(
Patente VARCHAR(10) NOT NULL PRIMARY KEY,
Seguro VARCHAR(80),
Modelo VARCHAR(40) NOT NULL,
Tipo VARCHAR(30) NOT NULL,
Color VARCHAR(15) NOT NULL,
Marca VARCHAR(20) NOT NULL,
DueNo INT UNSIGNED, 
FOREIGN KEY(DueNo)
REFERENCES Clientes (DNI)
);

CREATE TABLE Cod_Accidente(
ID INT UNSIGNED NOT NULL PRIMARY KEY,
Lugar VARCHAR(80) NOT NULL,
Fecha DATE NOT NULL,
Hora TIME NOT NULL,
Num_vehi INT UNSIGNED NOT NULL
);

CREATE TABLE Accidente_Ocurrido(
ID_Ocurrido INT UNSIGNED NOT NULL PRIMARY KEY,
ID_Vehiculo VARCHAR(10),
ID_Accidente INT UNSIGNED,
FOREIGN KEY (ID_Vehiculo)
REFERENCES Vehiculos (Patente),
FOREIGN KEY (ID_Accidente)
REFERENCES Cod_Accidente (ID)
);
