DROP DATABASE IF EXISTS Hospital;

CREATE DATABASE IF NOT EXISTS Hospital;

USE Hospital;

CREATE TABLE Medicos(
Matricula INT UNSIGNED PRIMARY KEY NOT NULL,
Nombre VARCHAR(30) NOT NULL,
DNI INT UNSIGNED UNIQUE NOT NULL,
Especialidad VARCHAR(80)
);

CREATE TABLE Pacientes(
DNI INT UNSIGNED NOT NULL PRIMARY KEY,
Grupo_Sanguineo VARCHAR(3) NOT NULL,
Nombre VARCHAR(30) NOT NULL,
Direccion VARCHAR(80) NOT NULL
);

CREATE TABLE Ingreso(
Num_Ingreso INT UNSIGNED PRIMARY KEY NOT NULL,
Cama INT UNSIGNED NOT NULL,
Diagnostico VARCHAR(100) NOT NULL,
Fecha DATE NOT NULL,
Paciente INT UNSIGNED NOT NULL,
FOREIGN KEY (Paciente)
REFERENCES Pacientes (DNI)  
);

CREATE TABLE Turnos(
Num_Turno INT UNSIGNED NOT NULL PRIMARY KEY,
Consultorio INT UNSIGNED NOT NULL,
Dia DATETIME NOT NULL UNIQUE,
Paciente INT UNSIGNED,
Medico INT UNSIGNED,
FOREIGN KEY (Medico)
REFERENCES Medicos (Matricula),
FOREIGN KEY (Paciente)
REFERENCES Pacientes (DNI)
);

