DELETE DATABASE Hospital IF EXISTS;

CREATE DATABASE Hospital IF NOT EXISTS;

USE Hospital;

CREATE TABLE(
Matricula
Nombre
DNI
Especialidad
);

CREATE TABLE Pacientes(
DNI INT UNSIGNED NOT NULL PRIMARY KEY
Grupo_Sanguineo VARCHAR(3) NOT NULL,
Nombre VARCHAR(30) NOT NULL,
Direccion VARCHAR(80) NOT NULL
);

CREATE TABLE(
Num_Ingreso INT UNSIGNED PRIMARY KEY NOT NULL,
Cama INT UNSIGNED NOT NULL,
Diagnostico VARCHAR(100) NOT NULL,
Fecha DATE NOT NULL,
Paciente INT UNSIGNED NOT NULL,
FOREIGN KEY (Paciente)
REFERENCES Pacientes (DNI)  
);

CREATE TABLE(
Num_Turno INT UNSIGNED NOT NULL PRIMARY KEY,
Consultorio INT UNSIGNED NOT NULL,
Dia DATETIME NOT NULL UNIQUE,
Paciente INT UNSIGNED,
Medico INT UNSIGNED,
FOREIGN KEY (Medico)
REFERENCES Medicos (Matricula)
FOREIGN KEY (Paciente),
REFERENCES Pacientes (DNI)
);

