DROP DATABASE IF EXISTS Tienda;

CREATE DATABASE IF NOT EXISTS Tienda;

USE Tienda;

CREATE TABLE Categorias(
Nombre VARCHAR(80) PRIMARY KEY NOT NULL
);

CREATE TABLE Productos(
Codigo INT UNSIGNED PRIMARY KEY NOT NULL,
Descripcion VARCHAR(30) NOT NULL,
Precio FLOAT UNSIGNED UNIQUE NOT NULL,
Stock INT UNSIGNED,
Categoria VARCHAR(50),
FOREIGN KEY(Categoria)
REFERENCES Categorias (Nombre)
);

CREATE TABLE Cupones(
Codigo INT UNSIGNED NOT NULL PRIMARY KEY,
Descuento INT UNSIGNED NOT NULL
);

CREATE TABLE Pedidos(
Num_Fact INT UNSIGNED PRIMARY KEY NOT NULL,
Estado ENUM("Pendiente", "Enviado", "Entregado") NOT NULL,
Fecha DATE NOT NULL,
Id_Producto INT UNSIGNED NOT NULL,
Cupon INT UNSIGNED,
FOREIGN KEY (Id_Producto)
REFERENCES Productos (Codigo),
FOREIGN KEY (Cupon)
REFERENCES Cupones (Codigo) 
);
